Admin.create!(
  email: "a@a",
  password: "aaaaaa"
  )

100.times do |n|
  Customer.create!(
    name: "テスト太郎#{n + 1}",
    nickname: "たろう",
    email: "test#{n + 1}@test.com",
    birthday: Date.new(1998, 12, 24),
    sex: 0,
    password: "aaaaaa",
    address: 13,
    is_valid: true,
    one_thing: "よろしくお願いします",
    hobby: "映画鑑賞",
    jobs: "テスト",
    annual_income: 7,
    marriage_history: "なし",
    children: 0,
    personality: 1,
    current_sign_in_at: Time.zone.now,
    army_flag: false
  )
end
  
100.times do |n|
  Customer.create!(
    name: "テスト花子#{n + 1}",
    nickname: "はなこ",
    email: "hanako#{n + 1}@hanako.com",
    birthday: Date.new(1998, 12, 24),
    sex: 1,
    password: "aaaaaa",
    address: 13,
    is_valid: true,
    one_thing: "よろしくお願いします",
    hobby: "音楽鑑賞",
    jobs: "テスト",
    annual_income: 7,
    marriage_history: "なし",
    children: 0,
    personality: 1,
    current_sign_in_at: Time.zone.now,
    army_flag: false
  )
end
  
Customer.create!(
    [
      {
        name: "石原さとみ",
        nickname: "さとみん",
        email: "b@b",
        birthday: Date.new(1986, 12, 24),
        sex: 1,
        password: "bbbbbb",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "映画鑑賞",
        jobs: "女優",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "橋本環奈",
        nickname: "かんなちゃん",
        email: "c@c",
        birthday: Date.new(1999, 2, 3),
        sex: 1,
        password: "cccccc",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "音楽鑑賞",
        jobs: "女優",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "浜辺美波",
        nickname: "みなみん",
        email: "d@d",
        birthday: Date.new(2000, 8, 29),
        sex: 1,
        password: "dddddd",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "たぴおか",
        jobs: "女優",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "綾瀬はるか",
        nickname: "はるちゃん",
        email: "e@e",
        birthday: Date.new(1985, 3, 21),
        sex: 1,
        password: "eeeeee",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "人間観察",
        jobs: "女優",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "有村架純",
        nickname: "かすみん",
        email: "f@f",
        birthday: Date.new(1993, 2, 13),
        sex: 1,
        password: "ffffff",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "カフェ巡り",
        jobs: "女優",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "新木優子",
        nickname: "ゆっこ",
        email: "g@g",
        birthday: Date.new(1993, 12, 15),
        sex: 1,
        password: "gggggg",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "写真・カメラ",
        jobs: "女優",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "山本舞香",
        nickname: "まいやん",
        email: "h@h",
        birthday: Date.new(1997, 10, 13),
        sex: 1,
        password: "hhhhhh",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "カラオケ",
        jobs: "女優",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "永野芽郁",
        nickname: "めいめい",
        email: "i@i",
        birthday: Date.new(1999, 9, 24),
        sex: 1,
        password: "iiiiii",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "英会話",
        jobs: "女優",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "森七菜",
        nickname: "なな",
        email: "j@j",
        birthday: Date.new(1999, 9, 24),
        sex: 1,
        password: "jjjjjj",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "料理",
        jobs: "女優",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "広瀬すず",
        nickname: "すずちゃん",
        email: "k@k",
        birthday: Date.new(1998, 6, 19),
        sex: 1,
        password: "kkkkkk",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "ファッション",
        jobs: "女優",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "本田翼",
        nickname: "ばっさー",
        email: "l@l",
        birthday: Date.new(1992, 6, 27),
        sex: 1,
        password: "llllll",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "ゲーム",
        jobs: "女優",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "吉沢亮",
        nickname: "よっしー",
        email: "aa@aa",
        birthday: Date.new(1994, 2, 1),
        sex: 0,
        password: "aaaaaa",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "イラスト",
        jobs: "俳優",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "新田真剣佑",
        nickname: "まっけん",
        email: "bb@bb",
        birthday: Date.new(1996, 11, 16),
        sex: 0,
        password: "bbbbbb",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "映画鑑賞",
        jobs: "俳優",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "ヒカキン",
        nickname: "ヒカキン",
        email: "cc@cc",
        birthday: Date.new(1989, 4, 21),
        sex: 0,
        password: "ccccccc",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "猫遊び",
        jobs: "YouTuber",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "伊野尾慧",
        nickname: "いのちゃん",
        email: "dd@dd",
        birthday: Date.new(1990, 6, 22),
        sex: 0,
        password: "dddddd",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "カフェ巡り",
        jobs: "アイドル",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "山崎賢人",
        nickname: "けん",
        email: "ee@ee",
        birthday: Date.new(1994, 9, 7),
        sex: 0,
        password: "eeeeee",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "資格所得",
        jobs: "俳優",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "川尻蓮",
        nickname: "れんくん",
        email: "ff@ff",
        birthday: Date.new(1997, 3, 2),
        sex: 0,
        password: "ffffff",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "ダンス",
        jobs: "アイドル",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "與那城奨",
        nickname: "よなぴー",
        email: "gg@gg",
        birthday: Date.new(1995, 10, 25),
        sex: 0,
        password: "gggggg",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "筋トレ",
        jobs: "アイドル",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "北村匠海",
        nickname: "たっくん",
        email: "hh@hh",
        birthday: Date.new(1997, 11, 3),
        sex: 0,
        password: "hhhhhh",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "一人旅",
        jobs: "俳優",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "佐藤健",
        nickname: "さとたけ",
        email: "jj@jj",
        birthday: Date.new(1989, 3, 21),
        sex: 0,
        password: "jjjjjj",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "読書",
        jobs: "俳優",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "川西拓実",
        nickname: "くみさん",
        email: "kk@kk",
        birthday: Date.new(1999, 6, 23),
        sex: 0,
        password: "kkkkkk",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "写真・カメラ",
        jobs: "アイドル",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "山下智久",
        nickname: "やまぴー",
        email: "ll@ll",
        birthday: Date.new(1985, 4, 9),
        sex: 0,
        password: "llllll",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "一人旅",
        jobs: "俳優",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "中村倫也",
        nickname: "とも",
        email: "mm@mm",
        birthday: Date.new(1986, 12, 24),
        sex: 0,
        password: "mmmmmm",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "スポーツ観戦",
        jobs: "俳優",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      },
      {
        name: "田中圭",
        nickname: "けい",
        email: "nn@nn",
        birthday: Date.new(1984, 7, 10),
        sex: 0,
        password: "mmmmmm",
        address: 13,
        is_valid: true,
        one_thing: "よろしくお願いします",
        hobby: "映画鑑賞",
        jobs: "俳優",
        annual_income: 7,
        marriage_history: "なし",
        children: 0,
        personality: 1,
        current_sign_in_at: Time.zone.now,
        army_flag: false
      }
    ]
  )